apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-EScxWPzMWp1o
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::717279725557:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-14T01:43:26Z"
  name: aws-auth
  namespace: kube-system
  uid: 334cbbae-e29b-4331-9389-fb02a92a82a7
