apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-EScxWPzMWp1o
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::717279725557:user/sindhu
      username: sindhu
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-10T16:18:55Z"
  name: aws-auth
  namespace: kube-system
  uid: 59ef73d1-d913-4cc5-9bed-7b0b5d8d9a57


